### ISSUE TITLE
Replayed show episodes are incorrectly handled as repeated

### ISSUE THREAD

**Issue by eliasbenb** [eliasbenb/PlexAniBridge#2]
**Describe the bug**

When a completed show has any episodes with a view count > 1, PlexAniBridge incorrectly considers it as repeated, regardless of if the rest of the episodes' view counts.

**To Reproduce**

1. Mark a show as completed by watching all episodes exactly once
2. Play one episode in the show an additional time
3. Run a sync
4. See that the show is now considered repeated (repeated count = 2)

**Expected behavior**

The show should still maintain a repeated count of 1 until all episodes in the show are watched a second time.

**Config (please list all config sections you set):**

In addition to all the required and default options:

- DESTRUCTIVE_SYNC=True

**Environment (how are you running PlexAniBridge):

- OS (Ubuntu 24.04)
- Docker [y]

**Comment by Shaykaden** [comment]
Hello, this issue is marked closed but it seems that the bug is still present. 
I have a series that was already marked “completed” but every episode I rewatch adds +1 to the “Total Rewatches”.

My docker-compose : 
```
services:
  plexanibridge:
    image: ghcr.io/eliasbenb/plexanibridge:latest
    environment:
      ANILIST_TOKEN: ${ANILIST_TOKENS}
      PLEX_TOKEN: ${PLEX_TOKEN}
      PLEX_USER: ${PLEX_USERS}
      PLEX_URL: http://plex:32400
      PLEX_SECTIONS: "[\"Japanimation\", \"Films d'animation\"]"
      SYNC_INTERVAL: 120
      # PARTIAL_SCAN: True
      # DESTRUCTIVE_SYNC: False
      # EXCLUDED_SYNC_FIELDS: ["notes", "score"]
      # DATA_PATH: ./data
      DRY_RUN: false
      # LOG_LEVEL: INFO
      # FUZZY_SEARCH_THRESHOLD: 90
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
```

If you need more information, don't hesitate to ask me.
