### ISSUE TITLE
Configuration file for multiple users

### ISSUE THREAD

**Issue by mizz141** [eliasbenb/PlexAniBridge#32]
**Is your feature request related to a problem? Please describe.**

When adding mulitple users, it can be really hard to keep track of which token belongs to which user, since those tokens are *really* long

**Describe the solution you'd like**

A configuration file, named "user_config" or similar, it should be possible to assign multiple users there, using some botched YAML as an example:

```
 entries:
   - user: Mizz141
     anilist_token:
       - [Anilist_token]
     sync_fields:
       - status
       - score
       - progress
       - repeat
       - notes
       - started_at
       - completed_at
      sync_intervall:
       - 3600
      destructive_sync:
      - false
      
   - user: Mizz142
     anilist_token:
       - [Anilist_token]
     sync_fields:
       - status
       - progress
       - repeat
       - started_at
       - completed_at 
      sync_intervall:
       - 7200
      destructive_sync:
      - true

```
      
**Describe alternatives you've considered**

Making a docker container for each user, now which I've goofed up and mixed tokens with other users, luckily this was found by using a dry-run

**Additional context**

The above solution could also allow for different sync types (destructive / non-destructive) and intervalls, depending on each users needs / wants.
